let curr_date=new Date()
let my_date=new Date("01-22-2004")
console.log(curr_date)
console.log(curr_date.toDateString())
console.log(curr_date.toString())
console.log(curr_date.toLocaleString())
console.log(curr_date.getTime())
console.log(my_date.getTime())
// console.log(curr_date.toLocaleString())
